### ISSUE TITLE
HelloSign.get_signature_requests does not work as expected

### ISSUE THREAD

**Issue by nishabn** [hellosign/hellosign-ruby-sdk#14]
HelloSign.get_signature_requests is supposed to take an array of signature_ids and return the status of those. But the actual behavior is that it returns the status of all documents in my hellosign account. 

For eg:  Following code fails since I do not have '42383e7327eda33f4b8b91217cbe95408cc1285f' in my account. This is from example in the documentation. But if I use HelloSign.get_signature_requests it returns all data in my account. 

```
pry(main)> signature_request = HelloSign.get_signature_request :signature_request_id => '42383e7327eda33f4b8b91217cbe95408cc1285f'
HelloSign::Error::NotFound: Server responded with code 404
Request URI: https://api.hellosign.com/v3/signature_request/42383e7327eda33f4b8b91217cbe95408cc1285f

```

**Comment by renderf0x** [comment]
Hi @nishabn -

Actually, the `get_signature_requests` method will list the signature requests you've sent through the API, and can be called without any arguments. So, the behavior you're seeing is accurate and correct.

Optionally, you can supply a parameter hash specifying a :page of results to fetch, and a :page_size - parameters that are useful when you have large numbers of results.

We don't currently have an endpoint that checks the status of multiple signature requests as you mention -- you'd have to either get all your requests with the above function and filter, or iterate and use `get_signature_request` (note the singular "request") to check each.

I'd be curious to know where you saw a reference to using `get_signature_requests` to check status, and providing an array as parameters, as I don't think this has ever been supported. Please let us know -- we be able to clear up any documentation that's confusing around that.

Thanks much!

//Derek
[Engineer @HelloSign]

**Comment by nishabn** [comment]
Ah  I see. The documentation here https://github.com/HelloFax/hellosign-ruby-sdk (in Usage) has reference to some thing like that. The comment says specific request but the api method used is get_signature_requests. 

> you'd have to either get all your requests with the above function and filter, or iterate and use get_signature_request (note the singular "request") to check each

Well yes, but would be nice to have array of signature_ids. Given that we might have lot of forms, doesn't scale to iterate through each of them. Same applies to get_signature_request as well. Do you have plans to support something like that ? How easy/difficult is to support such an endpoint ? 

-Nisha

**Comment by renderf0x** [comment]
Hi @nishabn -- sorry for the slow response.

Offhand I don't think it makes sense for us to create such an endpoint, since you can just use `get_sginature_requests` as in the example in Usage to grab all of your signature requests, and just filter to the ones you want locally.

The only use case I could see would be if you had a very, very large number of requests (too many to retrieve all of them at once) and wanted to retrieve a small, specific subset of them -- is this what you're experiencing?

Let me know and I can check into it.
