### ISSUE TITLE
prepare_files does not set mime_type when file is instance of ActionDispatch::Http::UploadedFile

### ISSUE THREAD

**Issue by bradwheel** [hellosign/hellosign-ruby-sdk#15]
version: v3

mime_type is missing the assignment operator.

Here is the line.
https://github.com/BradWheel/hellosign-ruby-sdk/blob/v3/lib/hello_sign/client.rb#L228

**Comment by bradwheel** [comment]
https://github.com/HelloFax/hellosign-ruby-sdk/pull/16

**Comment by renderf0x** [comment]
Thanks for the correction, Brad.
I've merged your PR in.
