### ISSUE TITLE
get_template {template_id} method returns error

### ISSUE THREAD

**Issue by arunumap** [hellosign/hellosign-ruby-sdk#17]
TypeError: no implicit conversion of Symbol into Integer

Need some help.

**Comment by renderf0x** [comment]
Hi @arunumap - how are you calling the get_template method?

You should be supplying the template ID keyed with :template_id, like so:

files = client.get_template_files :template_id => '39e3387f738adfa7ddd4cbd4c00d2a8ab6e4194b'

If that doesn't work for you please let us know with more information about how you're performing this call, either here, or via our API Support address at apisupport@hellosign.com

Cheers,

//Derek
