### ISSUE TITLE
Add ability to communicate via proxy

### ISSUE THREAD

**Issue by reedloden** [hellosign/hellosign-ruby-sdk#18]
Similar to New Relic's ruby gem (https://docs.newrelic.com/docs/agents/ruby-agent/installation-configuration/ruby-agent-configuration#general), need to be able to pass several proxy-related options to Faraday, including proxy_uri (encompasses host, port, scheme, etc.), proxy_user, and proxy_pass.

**Comment by cmpaul** [comment]
Looks good @reedloden -- thanks for the PR!

**Comment by reedloden** [comment]
@cmpaul, see also #21, which one of my colleagues submitted. Makes the use of a proxy slightly easier.

Thanks again for getting this merged and a release made so quickly.

**Comment by renderf0x** [comment]
Awesome, nice assist @reedloden . Just merged in #21 as well.

Cheers!
