### ISSUE TITLE
Why is 'pry' required?

### ISSUE THREAD

**Issue by AlexeyMK** [hellosign/hellosign-ruby-sdk#2]
I'm getting the following error on trying to startup my rails server:

```
/Users/alexey/.rvm/gems/ruby-2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- pry (LoadError)
```

Looking through your code, it looks like you use Pry for debugging (and maybe documentation) - pry is required in `lib/hello_sign/resource/resource_array.rb` but as far as I can tell is not used there directly.

Please either include `pry` explicitly in your Gemfile or remove the dependency.

**Comment by phallguy** [comment]
+1 Pry is a development gem and shouldn't be included in production.

**Comment by asolberg** [comment]
Sorry about that! Just removed the require 'pry' line, you're right that had no business in there.
