### ISSUE TITLE
#get_embedded_template_edit_url does not support skip_signer_roles/skip_subject_message

### ISSUE THREAD

**Issue by tyrbo** [hellosign/hellosign-ruby-sdk#23]
See: https://github.com/tyrbo/hellosign-ruby-sdk/blob/v3/lib/hello_sign/api/embedded.rb#L50-L64

Will open a pull request as well. A project I'm currently working on requires these options. I didn't see any specs for `#get_embedded_template_edit_url`.

**Comment by renderf0x** [comment]
Just merged in your PR. Thanks for the add!
