### ISSUE TITLE
Query not returning sorted results

### ISSUE THREAD

**Issue by radhack** [hellosign/hellosign-ruby-sdk#28]
I am using the ruby gem for hellosign and trying to search through the signature requests. I can't, no matter what parameters I give, sort through and find one by title.

**Comment by renderf0x** [comment]
What endpoint are you using, and how are you searching through them?

You should be able to pull down an array of your requests and iterate on them to find one...

**Comment by radhack** [comment]
That was a customer submission. I'll ask her to clarify, but her reason for even doing it is screwed up. She said "the signature id isn't saved anywhere" so she's searching by title to retrieve the sign url. My mind was blown, but I took her seriously and still submitted the GitHub issue. I also asked her to clarify what in the world she meant, as the signature id is stored on our side like a mofo.

**Comment by renderf0x** [comment]
So, looks like the Ruby SDK doesn't currently provide access to the search portion of the signature list api:

https://www.hellosign.com/api/reference#Search

Right now client.get_signature_requests will only accept

``` ruby
query = create_query_string(opts, [:page, :page_size, :ux_version])
# from signature_request.rb
```

This should be updated to accept a query as well.

It's on the list; thanks for the report!

**Comment by renderf0x** [comment]
@radhack just fixed this and pushed the gem.

If you update you should be able to use something like :query => "from: sherlock@holmes.com AND to: something@else.com"

CC: @desmondw
