### ISSUE TITLE
Where can I find a copy of the ruby-specific documentation online?

### ISSUE THREAD

**Issue by AlexeyMK** [hellosign/hellosign-ruby-sdk#3]
I've scoured through the https://www.hellosign.com/api/reference website, but can't seem to find the ruby-specific documentation. It's clearly available (given the formatted comments) but I can't seem to see an easy way to view it without generating it myself.

**Comment by asolberg** [comment]
Our Ruby specific documentation basically takes 3 forms 1) The Readme file in this repo, 2) The comment blocks in the codebase of this repo and 3) The ruby SDK examples on our website https://www.hellosign.com/api/reference. Those default to 'curl' but if you toggle one of them over to Ruby then the others will toggle as well.

**Comment by AlexeyMK** [comment]
Yeah - I just wish (and would strongly benefit from) having the comment
blocks extracted into their own web page (IE, hellosign.com/api/ruby-sdk/)
- it seems like they're formatted in a way built for a doc-generator;
  what's the motivation for not showing the decorated forms?

Also, (2) is really not discoverable from the README - you have to manually
realize to go to lib/hello_sign/api/signature_request.rb (
https://github.com/HelloFax/hellosign-ruby-sdk/blob/v3/lib/hello_sign/api/signature_request.rb)
to get to the 'good stuff'. At the least, a link to the relevant files in
the README would be nice.

Alexey

**Comment by asolberg** [comment]
We had considered separate SDK doc pages but realized much of the content would be duplicated in the comment blocks and our website (the examples there and the examples in the comment blocks are usually very similar if not identical). So in an effort to reduce maintenance we opted not to. But we may revisit this question in the future so thanks the feedback.
