### ISSUE TITLE
Consider renaming the gem

### ISSUE THREAD

**Issue by manuelmeurer** [hellosign/hellosign-ruby-sdk#34]
Unfortunately `hellosign-ruby-sdk` is not really a good gem name, `hellosign` or `hello_sign` would be much better. :smile: 

Currently one needs to add `gem 'hellosign-ruby-sdk', require: 'hello_sign'` to the Gemfile, since Bundler tries to load `lib/GEM_NAME.rb` and can't find `lib/hellosign-ruby-sdk.rb`. If the gem was named `hello_sign`, `lib/hello_sign.rb` would be loaded automatically.

An alternative to changing the gem name would be adding a `lib/hellosign-ruby-sdk.rb` file that requires `lib/hello_sign.rb`.

**Comment by renderf0x** [comment]
Heya @manuelmeurer --

Thanks, and I can see how that could definitely be a pain.

The issue with renaming to `hello_sign` is that that name is already taken by a third party vendor (https://rubygems.org/gems/hello_sign), so it's not available to us at this moment.

We're checking internally about options here -- we may consider a rename.

Re: the bundler issue -- is this new as of a recent version of bundler?
I haven't seen having to specify the require name in the Gemfile.

Though, as you point out, the name that's required in any ruby script files is `hello_sign` whereas the name of the gem is `hellosign-ruby-sdk`. Point taken.

**Comment by renderf0x** [comment]
@manuelmeurer -

Per your suggestion (thanks!), I created an additional require-able file `hellosign-ruby-sdk.rb` that references `hello_sign`. Should be a nice convenience!

Cheers for that - closing this out for now.

**Comment by manuelmeurer** [comment]
Great! :smile: 

Bundler has always worked that way AFAIK. Unless you added `require: false` to a gem in the Gemfile, it tries to load `lib/GEM_NAME.rb` from that gem. If it can't find it, nothing is loaded, so it's just a "convenience" thing I guess... :smile: 

What do you think about `hellosign` as the gem name? That was what I was looking for initially when searching for the official gem.

**Comment by renderf0x** [comment]
Huh. Well hopefully this will help that case at least.

Our API product head is going to be evaluating whether a change to `hellosign` would be a good step -- if it looks doable I'm sure we'll consider it. We'd like to avoid breaking anyone's existing implementation as much as possible though, so we'll have to weigh it carefully.

cc @rmelencio
