### ISSUE TITLE
Doesn't work for the getting the signed document URL

### ISSUE THREAD

**Issue by alexmac05** [hellosign/hellosign-ruby-sdk#42]
This ruby gem did not work to get the signed document URL

**Comment by kluzny** [comment]
It would be nice if we could get the pdf final version of a file using the gem's auth

```
sr = HelloSign.get_signature_requests(signature_request_id: "e72fcc55")
tempfile = sr.final_copy
```

Presently, I  receive the webhook event and have to manually use open-uri to auth and fetch down the file and attach it to my own s3 bucket.

**Comment by kluzny** [comment]
for anyone else checking issues, it's just not found in the docs: 
https://github.com/HelloFax/hellosign-ruby-sdk/blob/f8af9b3219e14222cf44172071339a8651e1f7ea/lib/hello_sign/api/signature_request.rb#L250
but the method is `HelloSign.signature_request_files`
