### ISSUE TITLE
Request: Parsable errors

### ISSUE THREAD

**Issue by jtmarmon** [hellosign/hellosign-ruby-sdk#44]
Right now errors are fairly useless except as a development tool. It's formatted as a big unparsable string you can't really do anything with. 

It would be ideal if errors could be parsed, like getting the response body, the request uri, and the status code.

**Comment by theoephraim** [comment]
Also need to add some more info in the docs so we can see how to catch and interact with the errors

**Comment by jyoung488** [comment]
Resolved in #45
