### ISSUE TITLE
Add 'role' to mandatory field in signature_request (for each entry in the 'signers' array)

### ISSUE THREAD

**Issue by AlexeyMK** [hellosign/hellosign-ruby-sdk#5]
In my experience, 'role' is mandatory, and you use it in your examples (https://www.hellosign.com/api/embeddedSigningExample), but it's not included in the comments above the function description.

Also, it would be nice to have a better sense of which of those fields are optional and which are not (for example, client_id is optional but the comment doesn't document it, only the code).

**Comment by AlexeyMK** [comment]
Also, it would be great if `role` was included in the response to creating a signature request, in each of the `signatures`.  Not a huge deal, but the easiest way to correlate them for me.

https://www.hellosign.com/api/embeddedSigningExample

**Comment by asolberg** [comment]
The signers[role] parameter is only relevant for using templates. You said role is not included in the comment blocks but it actually is if you look under create_embedded_signature_request_with_template and send_signature_request_with_template you'll see the 'role' parameter listed there. Regarding the idea of returning role in the response and documenting which parameters are mandatory vs. optional, that's good feedback, we'll consider adding that in the future.

**Comment by AlexeyMK** [comment]
Good point re: role - that clarifies a lot, thank you!
