### ISSUE TITLE
Unexpected error for exceeded_rate

### ISSUE THREAD

**Issue by ghost** [hellosign/hellosign-ruby-sdk#59]
I'm getting responses with status 429 when rate limit is exceeded, which isn't in ERRORS in HelloSign::Client, and thusly raises HelloSign::Error::UnknownError. 

The documentation here https://app.hellosign.com/api/reference#WarningsAndErrors suggests this should return 403 and raise HelloSign::Error::Forbidden.

I'm wondering if this is intentional, or if ERRORS and documentation just haven't been updated to match the actual api responses.

**Comment by ghost** [comment]
Opened https://github.com/HelloFax/hellosign-ruby-sdk/pull/60

**Comment by radhack** [comment]
Thanks for calling that out! The HTTPS CODE under [ErrorNames](https://app.hellosign.com/api/reference#ErrorNames) is incorrect for exceeded_rate - it's a 429.

Making a comment on the PR now too.

Thanks again!

**Comment by jyoung488** [comment]
Resolved in #60
