### ISSUE TITLE
Signature_request.custom_fields seems to want a Hash, not an Array<Hash>

### ISSUE THREAD

**Issue by AlexeyMK** [hellosign/hellosign-ruby-sdk#6]
The documentation in https://github.com/HelloFax/hellosign-ruby-sdk/blob/v3/lib/hello_sign/api/signature_request.rb is indecisive about whether custom_fields should be a Hash or an Array<Hash> (search the file for `custom_fields`) to see what I mean.

From using the API, the correct answer (this version) is a Hash.

**Comment by asolberg** [comment]
Ah, good catch, sorry for the confusion. It's definitely supposed to be a Hash not an Array. I'll update the comment block to reflect that.
