### ISSUE TITLE
No recipients specified

### ISSUE THREAD

**Issue by vsrboth** [hellosign/hellosign-ruby-sdk#65]
There seems to be the bug of the latest version.

This is my ruby codes:

```ruby
response =
 HelloSign.create_embedded_signature_request_with_template(
    :test_mode => 1,
    :client_id => 'e83be85a783e79d3093269486aa98540',
    :template_id => 'f674cfb4a0053a792adcae3bc5f7e0375630b91d',
    :subject => 'Embedded signature request',
    :message => 'Fill this in.',
    :signers => [
        {
            :email_address => 'jack@example.com',
            :name => 'Jack',
            :role => 'subject'
        }
    ]
)
```
I keep getting the following error:

```
Request URI: https://api.hellosign.com/v3/signature_request/create_embedded_with_template
Message: {"error":{"error_msg":"No recipients specified","error_name":"bad_request"}}
```

**Comment by caioariede** [comment]
Was having the same issue in the Python SDK, resolved it by changing role to `"Applicant"`

**Comment by caioariede** [comment]
Was having the same issue in the Python SDK, resolved it by using a role previously added for the template.

**Comment by radhack** [comment]
That's a good point @caioariede - @vsrboth double check that template_id has the role `'subject'` as a signer role (`:role` is case sensitive, so `'Subject'` in the code would fail if the role on the actual template was `'subject'`).

**Comment by radhack** [comment]
Hey @vsrboth - how's this looking? Did you get it to work?

**Comment by vsrboth** [comment]
@radhack I got it work just fine long ago :) You are right, the issue is the role :)
