### ISSUE TITLE
The Signers hash build on 3.6 seems to be breaking

### ISSUE THREAD

**Issue by brycesenz** [hellosign/hellosign-ruby-sdk#77]
We're using the `create_embedded_signature_request_with_template` without issue in version 3.5.4.  However, when we tried bumping up to v3.6, we noticed that sending in this:

```ruby
 signers: [{
    name: "John Doe",
    email_address: "jdoe@mail.com",
    role: "Applicant",
    order: 0
  }]
```
was being turned into a request in which our `signers` key was a Hash and not a URL.  E.g.

```ruby
 "signers[Applicant]": {
      "email_address": "jdoe@mail.com",
      "name": "John Doe",
      "order": "0"
    },
```

It feels like this should be an Array, correct?

**Comment by jyoung488** [comment]
Thank you! I'm using the latest version (updated today) of 3.6.1 but wasn't able to recreate the issue. I successfully created a signature request with the `create_embedded_signature_request_with_template` method using the same format for signers.

Please let me know if you continue running into issues and let us know by writing into apisupport@hellosign.com. Thank you again!
